Dating.Web/Models/ErrorViewModel.cs
using System;

namespace Dating.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Dating.Web/Controllers/DateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Dating.BusinessLayer.Interface;
using Dating.Entities;
using Microsoft.AspNetCore.Mvc;

namespace Dating.Web.Controllers
{
    public class DateController : Controller
    {
        private readonly IDateService _dateService;
        public DateController(IDateService dateService)
        {
            _dateService = dateService;

        }
        public IActionResult SendRequest()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> SendRequest(DateDetails dateDetails)
        {
          var result = await _dateService.SendRequest(dateDetails);
            if(result !=null)
            {
                ViewBag.message = result;
            }
            return View();
        }
    }
}

Dating.Web/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Dating.BusinessLayer.Interface;
using Dating.Entities;
using Microsoft.AspNetCore.Mvc;

namespace Dating.Web.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserService _userService;
        public UserController(IUserService userService)
        {
            _userService = userService;

        }


        public IActionResult Index()
        {
            try
            {
                return View();
            }
            catch (Exception exception)
            {
                return BadRequest(exception.Message);
            }
        }
        public IActionResult Login()
        {
            try
            {
                return View();
            }
            catch (Exception exception)
            {
                return BadRequest(exception.Message);
            }
        }
        [HttpPost]
        public async Task<IActionResult> Login(String UserName, String Password)
        {
            try
            {
                var result =await _userService.VerifyUser(UserName, Password);
                if(result !=null)
                {
                    return View("Index");
                }
                return View();
            }
            catch(Exception exception)
            {
                return BadRequest(exception.Message);
            }
            
        }
        public IActionResult CreateNewUser()
        {
            try
            {
                return View();
            }
            catch (Exception exception)
            {
                return BadRequest(exception.Message);
            }
        }

        [HttpPost]
        public async Task<IActionResult> CreateNewUser(User user)
        {
            //Business logic goes here
            try
            {
                var result =await _userService.CreateNewUser(user);
                if (result != null)
                {
                    return RedirectToAction("Login");
                }
                return View();
            }
            catch(Exception exception)
            {
                return BadRequest(exception.Message);
            }
          
        }



        public IActionResult AddProfile()
        {
            try
            {
                return View();
            }
            catch (Exception exception)
            {
                return BadRequest(exception.Message);
            }
        }

        public async Task<IActionResult> AllMembers()
        {
            try
            {
                var result = await _userService.ListOfMembers();
                return View(result);
            }
            catch (Exception exception)
            {
                return BadRequest(exception.Message);
            }
        }
        
        
        public IActionResult UserProfile(Profile profile)
        {
            try
            {
               return View(profile);
            }
            catch (Exception exception)
            {
                return BadRequest(exception.Message);
            }
        }
   

        [HttpPost]
        public async Task<IActionResult> AddProfile(Profile profile)
        {
            try
            {
                var result = await _userService.AddProfile(profile);
                if (result != null)
                {
                    return RedirectToAction("UserProfile","User",profile);
                }
                return View();
            }
            catch(Exception exception)
            {
                return BadRequest(exception.Message);
            }
            
        }
    }
}

Dating.Web/Views/Date/SendRequest.cshtml
@model Dating.Entities.DateDetails

@{
    ViewData["Title"] = "SendRequest";
}

<h1>SendRequest</h1>

<h4>DateDetails</h4>
<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="SendRequest">
            @if (ViewBag.message != null)
            {
                <div class="form-group">
                    <label class="control-label">ViewBag.message</label>
                    
                </div>
            }
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="RequestSenderName" class="control-label"></label>
                <input asp-for="RequestSenderName" class="form-control" />
                <span asp-validation-for="RequestSenderName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RequestReceiverName" class="control-label"></label>
                <input asp-for="RequestReceiverName" class="form-control" />
                <span asp-validation-for="RequestReceiverName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfRequest" class="control-label"></label>
                <input asp-for="DateOfRequest" class="form-control" />
                <span asp-validation-for="DateOfRequest" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RequestStatus" class="control-label"></label>
                <input asp-for="RequestStatus" class="form-control" />
                <span asp-validation-for="RequestStatus" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RequestSenderEmail" class="control-label"></label>
                <input asp-for="RequestSenderEmail" class="form-control" />
                <span asp-validation-for="RequestSenderEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RequestReceiverEmail" class="control-label"></label>
                <input asp-for="RequestReceiverEmail" class="form-control" />
                <span asp-validation-for="RequestReceiverEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Mobile" class="control-label"></label>
                <input asp-for="Mobile" class="form-control" />
                <span asp-validation-for="Mobile" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RequestMessage" class="control-label"></label>
                <input asp-for="RequestMessage" class="form-control" />
                <span asp-validation-for="RequestMessage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Send Request" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Dating.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Dating.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Dating.Web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Dating.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Dating.Web/Views/User/AddProfile.cshtml
@model Dating.Entities.Profile

@{
    ViewData["Title"] = "AddProfile";
}



<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddProfile">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label>
                <input asp-for="Gender" class="form-control" />
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Occupation" class="control-label"></label>
                <input asp-for="Occupation" class="form-control" />
                <span asp-validation-for="Occupation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AlternateEmail" class="control-label"></label>
                <input asp-for="AlternateEmail" class="form-control" />
                <span asp-validation-for="AlternateEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MobileNumber" class="control-label"></label>
                <input asp-for="MobileNumber" class="form-control" />
                <span asp-validation-for="MobileNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create Profile" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Dating.Web/Views/User/AllMembers.cshtml
@model IEnumerable<Dating.Entities.User>

@{
    ViewData["Title"] = "AllMembers";
}

<h1>AllMembers</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
           
            <th>
                @Html.DisplayNameFor(model => model.UserName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Password)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MobileNumber)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            
            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Password)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MobileNumber)
            </td>
            <td>
                @Html.ActionLink("Profile", "UserProfile","User") |
                
            </td>
        </tr>
}
    </tbody>
</table>

Dating.Web/Views/User/CreateNewUser.cshtml
@model Dating.Entities.User

@{
    ViewData["Title"] = "CreateNewUser";
}

<h1>CreateNewUser</h1>

<h4>User</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateNewUser">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MobileNumber" class="control-label"></label>
                <input asp-for="MobileNumber" class="form-control" />
                <span asp-validation-for="MobileNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Dating.Web/Views/User/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

    <div class="row">
        <div class="col-md-4">
            <form>
                <div class="form-group">
                    <div>
                        <a asp-action="AddProfile">Add Profile</a>
                    </div>
                </div>
                <div class="form-group">
                    <div>
                        <a asp-action="SendRequest" asp-controller="Date">Send Request</a>
                    </div>
                </div>
            </form>
        </div>
    </div>

Dating.Web/Views/User/Login.cshtml
@{
    ViewData["Title"] = "Login";
}



<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Login">
           
            
            <div class="form-group">
                <label class="control-label">UserName</label>
                <input id="UserName" name="UserName" class="form-control" required />
                
            </div>
            <div class="form-group">
                <label  class="control-label">Password</label>
                <input id="Password" name="Password" class="form-control" required />
                
            </div>
           
            <div class="form-group">
                <input type="submit" value="Login" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="CreateNewUser">Create New User</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Dating.Web/Views/User/UserProfile.cshtml
@model Dating.Entities.Profile

@{
    ViewData["Title"] = "User Profile";
}

<h1>UserProfile</h1>

<div>
    <h4>Profile</h4>
    <hr />
    <dl class="row">
       
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Gender)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Gender)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Occupation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Occupation)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AlternateEmail)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AlternateEmail)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MobileNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MobileNumber)
        </dd>
    </dl>
</div>